services:
  vote:
    build: 
      context: ./PythonVote
      target: dev 
    volumes:
      - ./PythonVote:/usr/local/app
    ports:
      - "5000:80"
    networks:
      - frotend
      - backend
    
  redis:
    build: 
      context: ./Redis
    ports:
      - "6379:6379"
    networks:
      - backend
  
  db:
    build: 
        context: ./bd
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - backend

  worker:
    build: 
      context: ./Worker
    networks:
      - backend

  result:
    build: ./result
    # use nodemon rather than node for local dev
    entrypoint: nodemon --inspect=0.0.0.0 server.js
    volumes:
      - ./result:/usr/local/app
    ports:
      - "5001:80"
      - "127.0.0.1:9229:9229"
    networks:
      - frotend
      - backend

networks:
  frotend:
  backend:

volumes:
  db-data: